services:
  - type: web
    name: autopulse-website
    env: static
    buildCommand: cd website && npm install && npm run build
    staticPublishPath: ./website/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
